"""
Django settings for syndication project.

Generated by 'django-admin startproject' using Django 1.10.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
from envparse import env

#REQUIRED ENVIRONMENT VARIABLES:
# django ---
# DJANGO_SECRET_KEY - secret key used
# mysql ---
# MYSQL_DB_NAME - name for mysql database
# MYSQL_USER - username for mysql with access to db
# MYSQL_PASSWORD - password for mysql access
# MYSQL_HOST - host that mysql server is located on
# MYSQL_PORT - port mysql is running on
# facebook ---
# FACEBOOK_CLIENT_ID - client_id for facebook application
# FACEBOOK_CLIENT_SECRET - secret used for facebook application

APPEND_SLASH = False
#GOOGLE_OAUTH2_CLIENT_SECRETS_JSON = os.path.join(os.path.dirname(__file__), 'google_secret.json')

GOOGLE_OAUTH2_CLIENT_ID = '775776867398-8c75dudorghpu6q5j0b6lt0tn7a1o0qq.apps.googleusercontent.com'

GOOGLE_OAUTH2_CLIENT_SECRET = 'hzU3B-08-65Xtrlel6iqxXLK'

GOOGLE_OAUTH2_SCOPES = (
    'email', 'profile')
#OPTIONAL ENVIRONMENT VARIABLES:
# debug ---
# DEBUG_ENABLED - set this environment variable to enable debug mode



# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'gagbwv&b6ycn0a^fboa08jgb@*o+xb0q-n%xj8*#sm2jx38((u'#env('DJANGO_SECRET_KEY')

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = env('DEBUG_ENABLED', cast=bool, default=False)
DEBUG = True
ALLOWED_HOSTS = ['127.0.0.1','localhost']#env('DJANGO_ALLOWED_HOSTS', cast=list)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'webapp',
    'oauth2client.contrib.django_util'
]

#ADMINS = (
#    ('Stanislav', 'stanislavgrozny@gmail.com'),
#)

#MANAGERS = ADMINS

MIDDLEWARE = [
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
]
MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)
ROOT_URLCONF = 'syndication.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'syndication.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    # 'default': {
        # 'ENGINE': 'django.db.backends.mysql',
        # 'NAME': env('MYSQL_DB_NAME'),
        # 'USER': env('MYSQL_USER'),
        # 'PASSWORD': env('MYSQL_PASSWORD'),
        # 'HOST': env('MYSQL_HOST'),
        # 'PORT': env('MYSQL_PORT')
    # }
    'default': {
      'ENGINE': 'django.db.backends.sqlite3',
    'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
	}
	
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/syndication_static/'

# FACEBOOK_SETTINGS = {
    # 'client_id': env('FACEBOOK_CLIENT_ID'),
    # 'client_secret': env('FACEBOOK_CLIENT_SECRET')
# }
