# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventInfo',
            fields=[
                ('EventID', models.AutoField(primary_key=True, serialize=False)),
                ('EventName', models.CharField(max_length=50)),
                ('EventDescription', models.TextField()),
                ('EventLocation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('TripID', models.AutoField(primary_key=True, serialize=False)),
                ('EventStart', models.DateTimeField()),
                ('EventEnd', models.DateTimeField()),
                ('PostingID', models.IntegerField()),
                ('EventID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.EventInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Postings',
            fields=[
                ('PostingID', models.AutoField(primary_key=True, serialize=False)),
                ('Facebook', models.BooleanField()),
                ('MeetUp', models.BooleanField()),
                ('EventBrite', models.BooleanField()),
                ('TripID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.EventLog')),
            ],
        ),
    ]
