# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 02:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=50)),
                ('key', models.TextField()),
                ('lastUpdated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventName', models.CharField(max_length=50)),
                ('EventDescription', models.TextField()),
                ('EventMeetLocation', models.CharField(max_length=50)),
                ('EventDestination', models.CharField(max_length=50)),
                ('EventStart', models.DateTimeField()),
                ('EventEnd', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Postings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GoogleCal', models.BooleanField(default=False)),
                ('Facebook', models.BooleanField(default=False)),
                ('MeetUp', models.BooleanField(default=False)),
                ('EventBrite', models.BooleanField(default=False)),
                ('LICCB', models.BooleanField(default=False)),
                ('EventID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.EventInfo')),
            ],
        ),
    ]
