# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinfo',
            name='PostingID',
            field=models.IntegerField(default=0),
        ),
    ]
