# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=50)),
                ('key', models.TextField()),
                ('lastUpdated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='eventinfo',
            name='PostingID',
            field=models.IntegerField(default=0),
        ),
    ]
