# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-02 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20170301_0030'),
        ('webapp', '0002_auto_20170301_1714'),
    ]

    operations = [
    ]
