# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-27 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20170322_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'permissions': (('CanLogin', 'Allows user to login'), ('CreatePage_View', 'Can view the create page'), ('CreatePage_Action', 'Can create events'), ('PublishPage_View', 'Can view publish page'), ('PublishPage_Action', 'Can publish events'), ('StatusPage_View', 'Can view status of events'), ('StatusPage_Edit', 'Can edit posted events'), ('StatusPage_Delete', 'Can  delete posted events'), ('CanChangePermissions', 'can change permissions'), ('CanChangeGroups', 'Can change groups'), ('CanChangeAPIKeys', 'Can change API keys'), ('CanViewLogs', 'Can view logs')),
            },
        ),
        migrations.CreateModel(
            name='LICCB_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GroupName', models.CharField(max_length=256)),
                ('Email', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='LICCB_Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentId', models.IntegerField()),
                ('parentType', models.IntegerField()),
                ('childId', models.IntegerField()),
                ('childType', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LICCB_Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoleName', models.CharField(max_length=256)),
                ('CanLogin', models.BooleanField(default=True)),
                ('CreatePage_View', models.BooleanField(default=False)),
                ('CreatePage_Action', models.BooleanField(default=False)),
                ('PublishPage_View', models.BooleanField(default=False)),
                ('PublishPage_Action', models.BooleanField(default=False)),
                ('StatusPage_View', models.BooleanField(default=False)),
                ('StatusPage_Edit', models.BooleanField(default=False)),
                ('StatusPage_Delete', models.BooleanField(default=False)),
                ('CanChangePermissions', models.BooleanField(default=False)),
                ('CanChangeGroups', models.BooleanField(default=False)),
                ('CanAssignRoles', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LICCB_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=256)),
                ('Email', models.CharField(max_length=256)),
                ('FirstName', models.CharField(max_length=256)),
                ('LastName', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='postings',
            name='EventID',
        ),
        migrations.DeleteModel(
            name='Postings',
        ),
    ]
