# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_google_service_fixed'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinfo',
            name='Availability',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='eventinfo',
            name='Fee',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='eventinfo',
            name='PoCEmail',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='eventinfo',
            name='PoCName',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='eventinfo',
            name='PoCNumber',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='eventinfo',
            name='RegistrationLink',
            field=models.URLField(),
        ),
    ]
