# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-02 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_google_service_fixed'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'permissions': (('CanLogin', 'Allows user to login'), ('CreatePage_View', 'Can view the create page'), ('CreatePage_Action', 'Can create events'), ('PublishPage_View', 'Can view publish page'), ('PublishPage_Action', 'Can publish events'), ('StatusPage_View', 'Can view status of events'), ('StatusPage_Edit', 'Can edit posted events'), ('StatusPage_Delete', 'Can  delete posted events'), ('CanChangePermissions', 'can change permissions'), ('CanChangeGroups', 'Can change groups'), ('CanChangeAPIKeys', 'Can change API keys'), ('CanViewLogs', 'Can view logs')),
            },
        ),
        migrations.CreateModel(
            name='LICCB_Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoleName', models.CharField(max_length=256)),
                ('Groups', models.CharField(blank=True, max_length=2048)),
                ('Users', models.CharField(blank=True, max_length=2048)),
                ('CanLogin', models.BooleanField(default=True)),
                ('CreatePage_View', models.BooleanField(default=False)),
                ('CreatePage_Action', models.BooleanField(default=False)),
                ('PublishPage_View', models.BooleanField(default=False)),
                ('PublishPage_Action', models.BooleanField(default=False)),
                ('StatusPage_View', models.BooleanField(default=False)),
                ('StatusPage_Edit', models.BooleanField(default=False)),
                ('StatusPage_Delete', models.BooleanField(default=False)),
                ('CanChangePermissions', models.BooleanField(default=False)),
                ('CanChangeGroups', models.BooleanField(default=False)),
                ('CanChangeAPIKeys', models.BooleanField(default=False)),
                ('CanViewLogs', models.BooleanField(default=False)),
            ],
        ),
    ]
