# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-27 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20170426_2217'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LICCB_Group',
        ),
        migrations.DeleteModel(
            name='LICCB_Relationship',
        ),
        migrations.DeleteModel(
            name='LICCB_User',
        ),
        migrations.AddField(
            model_name='liccb_role',
            name='Children',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
