# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-03 03:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_wordpress'),
        ('webapp', '0004_globalpermissions_liccb_role'),
    ]

    operations = [
    ]
