# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-27 04:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20170427_0033'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LICCB_Role',
        ),
    ]
