# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-27 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_delete_liccb_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='LICCB_Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoleName', models.CharField(max_length=256)),
                ('Children', models.CharField(blank=True, max_length=2048)),
                ('CanLogin', models.BooleanField(default=True)),
                ('CreatePage_View', models.BooleanField(default=False)),
                ('CreatePage_Action', models.BooleanField(default=False)),
                ('PublishPage_View', models.BooleanField(default=False)),
                ('PublishPage_Action', models.BooleanField(default=False)),
                ('StatusPage_View', models.BooleanField(default=False)),
                ('StatusPage_Edit', models.BooleanField(default=False)),
                ('StatusPage_Delete', models.BooleanField(default=False)),
                ('CanChangePermissions', models.BooleanField(default=False)),
                ('CanChangeGroups', models.BooleanField(default=False)),
                ('CanAssignRoles', models.BooleanField(default=False)),
            ],
        ),
    ]
