# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-27 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_liccb_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liccb_role',
            old_name='CanAssignRoles',
            new_name='CanChangeAPIKeys',
        ),
        migrations.RenameField(
            model_name='liccb_role',
            old_name='Children',
            new_name='Groups',
        ),
        migrations.AddField(
            model_name='liccb_role',
            name='CanViewLogs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='liccb_role',
            name='Users',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
